services:
  - type: web
    name: pavan-files
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        sync: false
      - key: APP_PASSWORD
        sync: false
